name: Generate Sitemaps Daily

on:
  schedule:
    - cron: "30 20 * * *"  # 2:00 AM IST daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Generate sitemap
        run: node scripts/generate-sitemap.mjs

      - name: Commit and push updated sitemap
        run: |
          git config --global user.name "Sitemap Bot"
          git config --global user.email "bot@newshubnow.in"
          git add public/sitemap.xml public/news-sitemap.xml || echo "No sitemap files"
          git commit -m "🔁 auto: update sitemap [skip ci]" || echo "No changes to commit"
          git push origin main
        env:
          # GitHub automatically provides write access using this token
          GIT_AUTHOR_NAME: Sitemap Bot
          GIT_AUTHOR_EMAIL: bot@newshubnow.in
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
